services:
  postgres:
    image: postgres:16.8-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: